Repository le-mystere-de-la-salle-jaune/evalme-back, pull requests merged in 2018-07, with the labels that each got.

#4 Configuration XML Duel
  src/main/resources/jdd/jdd-Duel.xml
  src/test/java/dev/entites/JddDuelTest.java
Labels: enhancement

#26 Josias NTUAREMBA
  src/main/java/dev/controller/ConcoursController.java
  src/main/java/dev/metiers/ConcoursService.java
  src/main/java/dev/repositories/concours/ConcoursRepository.java
  src/main/java/dev/repositories/concours/ConcoursRepositoryMemoire.java
  src/main/resources/jdd/jdd-concours.xml
  src/main/webapp/WEB-INF/views/concours/listerConcours.jsp
Labels: CRUD - List

#39 Redor Mathieu
  src/main/java/dev/controller/OptionQuestionController.java
  src/main/java/dev/controller/QuestionController.java
  src/main/java/dev/entites/OptionQuestion.java
  src/main/java/dev/entites/Question.java
  src/main/webapp/WEB-INF/views/questions/supprimerOptionQuestions.jsp
  src/main/webapp/WEB-INF/views/questions/supprimerQuestions.jsp
Labels: CRUD - Delete

#38 CRUD Duel
  src/main/java/dev/controller/duel/DuelController.java
  src/main/java/dev/metiers/DuelService.java
  src/main/resources/jdd/jdd-Duel.xml
  src/main/webapp/WEB-INF/views/duels/ajouterDuel.jsp
  src/main/webapp/WEB-INF/views/duels/editerDuel.jsp
  src/main/webapp/WEB-INF/views/duels/listerDuels.jsp
  src/test/java/dev/entites/JddDuelTest.java
Labels: CRUD - Add, CRUD - Delete, CRUD - List, CRUD - Update, To review

#40 service stagiaire delete
  src/main/java/dev/controller/StagiaireController.java
  src/main/java/dev/metiers/StagiaireService.java
  src/main/webapp/WEB-INF/views/stagiaires/creerStagiaires.jsp
  src/main/webapp/WEB-INF/views/stagiaires/editerStagiaires.jsp
  src/main/webapp/WEB-INF/views/stagiaires/listerStagiaires.jsp
  src/main/webapp/WEB-INF/views/stagiaires/supprimerStagiaires.jsp
Labels: CRUD - Delete

#43 Quizz - Editer
  src/main/java/dev/controller/QuizzController.java
  src/main/java/dev/entites/Quizz.java
  src/main/java/dev/metiers/QuizzService.java
  src/main/java/dev/repositories/BaseRepositoryMemoire.java
  src/main/webapp/WEB-INF/views/quizzes/listerQuizz.jsp
Labels: CRUD - Update

#41 Examen supression
  src/main/java/dev/controller/ExamenController.java
  src/main/java/dev/controller/QuizzController.java
  src/main/java/dev/metiers/ClasseService.java
  src/main/java/dev/metiers/ExamenService.java
  src/main/java/dev/repositories/stagiaire/StagiaireRepositoryMemoire.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/views/examens/ajouterExamen.jsp
  src/main/webapp/WEB-INF/views/examens/editerExamen.jsp
  src/main/webapp/WEB-INF/views/examens/listerExamens.jsp
Labels: CRUD - Delete, To review

#42 Redor Mathieu : Question/OptionQuestion -> Amélioration de la navigation CRUD
  src/main/java/dev/controller/OptionQuestionController.java
  src/main/java/dev/controller/QuestionController.java
  src/main/webapp/WEB-INF/views/questions/listerOptionQuestions.jsp
  src/main/webapp/WEB-INF/views/questions/listerQuestions.jsp
Labels: CRUD - Add, CRUD - Delete, CRUD - List, CRUD - Update

#44 Quizz - Supprimer
  src/main/java/dev/controller/QuizzController.java
  src/main/webapp/WEB-INF/views/quizzes/listerQuizz.jsp
Labels: CRUD - Delete

#45 CRUD Complet opérationel
  src/main/java/dev/controller/ClasseController.java
  src/main/java/dev/metiers/ClasseService.java
  src/main/java/dev/repositories/classe/ClasseRepositoryMemoire.java
  src/main/resources/bdd/data.sql
  src/main/webapp/WEB-INF/views/classes/listerClasses.jsp
  src/main/webapp/WEB-INF/views/classes/majClasse.jsp
  src/main/webapp/WEB-INF/views/classes/supprimerClasses.jsp
  src/main/webapp/WEB-INF/views/structure.css
Labels: CRUD - Add, CRUD - Delete, CRUD - List, CRUD - Update

#73 Exam jpa spring
  src/main/java/dev/controller/ExamenController.java
  src/main/java/dev/controller/api/ExamenApiController.java
  src/main/java/dev/controller/api/viewModels/BaseVm.java
  src/main/java/dev/controller/api/viewModels/ClasseVm.java
  src/main/java/dev/controller/api/viewModels/ExamenVm.java
  src/main/java/dev/controller/api/viewModels/QuizzVm.java
  src/main/java/dev/entites/Examen.java
  src/main/java/dev/metiers/ExamenService.java
  src/main/java/dev/repositories/examen/ExamenDataJpaRepo.java
  src/main/java/dev/repositories/examen/ExamenRepositoryDataJpa.java
  src/main/java/dev/repositories/examen/ExamenRepositoryJpa.java
  src/main/java/dev/repositories/note/NoteDataJpaRepo.java
  src/main/java/dev/repositories/quizz/QuizzDataJpaRepo.java
  src/main/java/dev/repositories/quizz/QuizzRepositoryDataJpa.java
  src/main/java/dev/repositories/quizz/QuizzRepositoryJdbc.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema-postgres.sql
  src/main/webapp/WEB-INF/views/examens/editerExamen.jsp
  src/test/java/dev/repositories/examen/ExamenRepositoryDataJpaTest.java
Labels: To review

#82 fixes
  pom.xml
  src/main/java/dev/entites/OptionQuestion.java
  src/main/java/dev/entites/Question.java
  src/main/resources/schema-mysql.sql
  src/main/resources/schema-postgres.sql
  src/main/webapp/WEB-INF/views/connexion.jsp
Labels: To review

#89 commit ajout update API
  src/main/java/dev/controller/api/ExamenApiController.java
  src/main/java/dev/controller/api/viewModels/examen/ExamenVmUtil.java
Labels: API Update

#79 Redor Mathieu - Data-JPA
  pom.xml
  src/main/java/dev/entites/OptionQuestion.java
  src/main/java/dev/entites/Question.java
  src/main/java/dev/repositories/question/OptionQuestionAppConfig.java
  src/main/java/dev/repositories/question/OptionQuestionDataJpaRepo.java
  src/main/java/dev/repositories/question/OptionQuestionRepositoryDataJpa.java
  src/main/java/dev/repositories/question/OptionQuestionRepositoryJpa.java
  src/main/java/dev/repositories/question/OptionQuestionRepositoryMemoire.java
  src/main/java/dev/repositories/question/QuestionAppConfig.java
  src/main/java/dev/repositories/question/QuestionDataJpaRepo.java
  src/main/java/dev/repositories/question/QuestionRepositoryDataJpa.java
  src/main/java/dev/repositories/question/QuestionRepositoryMemoire.java
  src/main/resources/data.sql
  src/main/resources/schema-mysql.sql
  src/main/resources/schema-postgres.sql
  src/main/webapp/WEB-INF/views/questions/creerOptionQuestions.jsp
  src/main/webapp/WEB-INF/views/questions/creerQuestions.jsp
  src/main/webapp/WEB-INF/views/questions/majOptionQuestions.jsp
  src/main/webapp/WEB-INF/views/questions/majQuestions.jsp
  src/test/java/dev/config/DataJpaTestConfig.java
  src/test/java/dev/repositories/question/OptionQuestionRepositoryDataJpaTest.java
  src/test/java/dev/repositories/question/OptionQuestionRepositoryJpaTest.java
  src/test/java/dev/repositories/question/OptionQuestionRepositoryMemoireTest.java
  src/test/java/dev/repositories/question/QuestionRepositoryDataJpaTest.java
  src/test/java/dev/repositories/question/QuestionRepositoryMemoireTest.java
Labels: CRUD - Add, CRUD - Delete, CRUD - List, CRUD - Update, To review

#90 Lister + lister détail API
  src/main/java/dev/controller/api/viewModels/classe/BaseVm.java
  src/main/java/dev/controller/api/viewModels/classe/ClasseApiController.java
  src/main/java/dev/controller/api/viewModels/classe/ClasseVmAjouter.java
  src/main/java/dev/controller/api/viewModels/classe/ClasseVmDetail.java
  src/main/java/dev/controller/api/viewModels/classe/ClasseVmLister.java
  src/main/java/dev/controller/api/viewModels/classe/StagiaireVmDetail.java
  src/main/java/dev/controller/api/viewModels/examen/ClasseVm.java
Labels: API LISTER, API LISTER BY ID

#91 modification pour suppression examen avec note
  src/main/java/dev/controller/api/ExamenApiController.java
  src/main/java/dev/metiers/ExamenService.java
Labels: API SUPPRIMER, To review

#85 WEB API : Administrer Questions
  pom.xml
  src/main/java/dev/controller/api/questions/ListerQuestionApiController.java
  src/main/java/dev/controller/api/questions/QuestionBuilder.java
  src/main/java/dev/controller/api/questions/viewModels/ListerQuestionVM.java
  src/main/java/dev/controller/api/questions/viewModels/OptionListerQuestionVM.java
  src/main/java/dev/controller/api/questions/viewModels/QuestionByIdVM.java
  src/main/java/dev/metiers/QuestionService.java
  src/main/java/dev/repositories/question/OptionQuestionRepositoryMemoire.java
  src/main/resources/jdd/jdd-question.xml
  src/test/java/dev/repositories/question/OptionQuestionRepositoryMemoireTest.java
  src/test/java/dev/repositories/question/QuestionRepositoryMemoireTest.java
Labels: API LISTER, API LISTER BY ID, To review
